### ISSUE TITLE
(Question) How to bind input parameters

### ISSUE THREAD

**Issue by raijinsetsu** [shlomiassaf/angular2-modal#108]
I am placing a component into the modal window like so:
```
// Setup the modal window
let op = new BSModalContext();
op.isBlocking = false;
op.keyboard = 27;
op.size = 'lg';

// Open the object-view component in a modal window
this._modal
    .open(ObjectView, op);
```
Here is what the component looks like:
```
@Component({...})
export class ObjectView {
@Input() def: any
...
```

How would I pass a value in for the 'def' property?

It seems like the 3rd argument, bindings, is not the correct place: it looks like it's for injection and not property binding.

**Comment by shlomiassaf** [comment]
Hi,

The modal acts as an isolated component that you can fire from anywhere in you'r app.

You can think of the design similer to event driven approach where you fire a modal and get a reponse in the form of a promise.
 
Since it's a component you can bind thing inside it, template to component instance.

If you want to update things outside of the modal you register to the promise and update once modal is fired.

If you want to update things while the modal is running you can do it in several ways, I can think of two right now:

1) inject a service and communicate via services
2) supply an observable and use it to stream data

In most cases you will fire the modal from a component, that can be a page or a child in a page, supply an observable and bind that observable in your page and you have bindings...

It doesn't make much sense to supply `@Input` bindings to properties outside of the modal since the modal is not part of the component/template you're firing it from, it's isolated.

This is a solid design and common for modal's, you also have solid ways to communicate

**Comment by raijinsetsu** [comment]
Here... Let me add more to the code to make it clearer because I am already doing everything you are saying. I just do not see the way to pass input parameters into the .open call on modal.

The application has "<parent-component></parent-component>" as it's template. That component is defined like this:
```
@Component({
    selector: 'parent-component',
    template: `<button (click)="openModal()">Open!</button>`
})
export class ParentComponent {

    currentItem: any;

    constructor(private _modal: Modal) {
    }

    openModal() {
        // Setup the modal window
        let op = new BSModalContext();
        op.isBlocking = false;
        op.keyboard = 27;
        op.size = 'lg';

        // Open the object-view component in a modal window
        this._modal
            .open(ChildComponent, op);
    }
}
```
I want the child component to appear within the modal dialog opened by the openModel() function. That component has this definition:
```
@Component({
    selector: 'child-component',
    template: '<div>CHILD!!!</div>'
})
export class ChildComponent {
    @Input() item: any;
}
```

I want to take the currentItem value from ParentComponent and pass in to the call to _modal.open so that the ChildComponent has that information.

**Comment by shlomiassaf** [comment]
See this: https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/app/bootstrap-demo/bootstrap-demo-page/bootstrap-demo-page.ts#L53

I'm passing the information (2, 3) to the modal window, in this case the child component takes 2+3 and display them.

This is the code for the child component.
https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/app/bootstrap-demo/bootstrap-demo-page/custom-modal-sample.ts

**Comment by raijinsetsu** [comment]
So I have to extend the ModalContext class to add in my own values and the
injector will pass that to the constructor for the component.
It's not as straight-forward as I'd hoped, but it's workable.

Thanks

**Comment by shlomiassaf** [comment]
@raijinsetsu You don't have to extend ModalContext, there are simple built in dialogs.

If you want custom behaviour and custom UI, yes you need a custom component.
The other option is a custom template.

You can use custom templates now but it will require a custom component first, to handle custom templates. 

I will add support to custom templates, built in, once RC2 is out with the new `NgOutletContext` support.

**Comment by Mario-Eis** [comment]
How is it done using DialogPresetBuilder?

**Comment by shlomiassaf** [comment]
I'll close this stale issue, please re-open with a comment if it still an issue.
