### ISSUE TITLE
How I can add custom component in popup body

### ISSUE THREAD

**Issue by FRAGnatt** [shlomiassaf/angular2-modal#118]
I have "component1" and "component2"

In component1 I want to call this code
this.modal.alert()
                .size('lg')
                .showClose(true)
                .title('MyTitle')
                .body('\<component2\>\</component2>')
                .open();

But angular2 didn't parse \<component2\>, How I can fix that ?

At the future, I want to get data from component2 to component1

**Comment by shlomiassaf** [comment]
Body does not accept template syntax since, this is due to angular restrictions concerning the offline compilation feature in angular 2.

Instead do
```
this.modal.alert()
.component(Component2)
.size('lg')
.showClose(true)
.title('MyTitle')
.open();
```

**Comment by shlomiassaf** [comment]
In this repository, see the demo app, it implements all of the above, from custom components to custom plugins.

Sadly, there aren't any docs since I don't have the time to write them but I will be happy to add it if someone from the community will pick up the globe and do it.

Currently, you need to see how it's implemented in the docs and in the plugin code and do it. It's not that complicated.

Note however, that the issues in github are not for support. Limited support is fine but in general I don't have the time to maintain and support at the same time.

**Comment by steven-nguyen-hcm** [comment]
Thank you for your answer. This is my problem too. But how can I give an input to component2?

**Comment by ashwinirajput** [comment]
onCheck() {
    this.modal.alert()
        .size('lg')
        .showClose(true)
        .title('Hi Angular 2')
        .body(`
              <add-client></add-client>
            `)
        .open();
  }
