### ISSUE TITLE
(QUESTION) How to use templateUrl with Custom Modal Component

### ISSUE THREAD

**Issue by LifeguardConcepts** [shlomiassaf/angular2-modal#147]
Is there functionality exposed to use a templateUrl instead of the inline template when implementing a custom component to display the modal content?

**Comment by Slaals** [comment]
I was looking for a way to do this. It appears that you have to create a new component which must extends `ModalComponent`. Since it's a component, you can put a template url aswell. See this code [here](https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/app/bootstrap-demo/bootstrap-demo-page/custom-modal-sample.ts).

Then, to call it, you have to instantiate the component you created, you can see this [here](https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/app/bootstrap-demo/bootstrap-demo-page/bootstrap-demo-page.ts#L52).

I'll try this by myself and come back later if I have anything to add or if you still need helps.

It would be great if someone add the method to the walkthrough.

**Comment by LifeguardConcepts** [comment]
@Slaals When I tried with a templateUrl on the component the modal opened with a grayed overlay on the parent div but no modal dialog.  I looked at the network calls and didn't see any attempt to load the templateUrl.  Any luck on your side?

**Comment by LifeguardConcepts** [comment]
@Slaals, well nevermind I must have had some bad class definitions in my template.  Worked great!
