### ISSUE TITLE
Demo of Overlay Context options in Custom Bootstrap Modal

### ISSUE THREAD

**Issue by scottmbulloch** [shlomiassaf/angular2-modal#166]
I'm trying to implement the inElement and isBlocking features on a custom BS modal. I believe this should be trivial but I cannot figure where to pass these options. I found where these are defined in [overlay-context.ts](https://github.com/shlomiassaf/angular2-modal/blob/master/src/components/angular2-modal/models/overlay-context.ts) and I think they should go into [BSModalContextBuilder](https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/app/bootstrap-demo/bootstrap-demo-page/bootstrap-demo-page.ts#L46) but everything I have tried has failed. Can you add an example of this?

**Comment by shlomiassaf** [comment]
What version are you using? I'll answer considering the latest version (2.0.0-beta.10)

There are 2 factors you need to consider when placing a modal inside an element.
1) setting `inElement` to true
2) setting the viewContainerRef to place the element in

(1) will make sure the overlay is styles accordingly (position absolute instead of fixed and some other styles needed)
It should be in **overlay-context.ts** (`OverlayContextBuilder`) since overlay is the element that goes inside another element and of course it's a feature not unique to the bootstrap plugin but to **any** plugin out there (e.g VEX plugin... and others to come)

Anyway, `BSModalContextBuilder` inherit `OverlayContextBuilder` :)

(2) A `ViewContainerRef` is needed so the library can inject the overlay element as a child element of the bounding element, i.e: the overlay is **inElement** referenced by `viewContainerRef`

Getting a reference to a `ViewContainerRef` has some boilerplate so I'v added a directive to help with that, its is called `overlayTarget` and it acts as a global key value store for ViewContainerRefs, where key is some id of type string.

```
<div overlayTarget="my-overlay-target"></div>
```

Now the store has a reference to a viewContainerRef representing the `div`

The library has 3 drop in helpers: alert, propt & confirm which make it easy to use the above
```ts
modal.alert().inElement(true).open('my-overlay-target');
```
Simple...
You can easily build a plugin that has a custom component and the above drop ins.
The demo application has a [ad-hoc plugin](https://github.com/shlomiassaf/angular2-modal/tree/master/src/demo/app/home/in-app-plugin) that show's how easy it is.

For custom components without a plugin you need to use the `open()` method which requires 2 parameters, the custom component class and an 'OverlayConfig'

Drop-ins create the 'OverlayConfig' for the user, making dialog creation easy.
If we're using the bootstrap plugin we can "mimic" this behavior like this:

```ts
// this is the context that the custom component use.
// the custom component gets a `DialogRef` injected into it, which has `DialogRef.context` 
class CustomModalContext extends BSModalContext {
  public num1: number;
  public num2: number;
}
          const builder = new BSModalContextBuilder<CustomModalContext>(
            { num1: 2, num2: 3 } as any, // here we pre-set the context
            undefined,
            CustomModalContext // hinting the builder we're using this context class so it will init it.
          );

          let overlayConfig: OverlayConfig = {
            viewContainer: 'my-overlay-target', // setting the view container ref via id
            context: builder.inElement(true).toJSON() // setting inElement to true
          };

          let dialogRef = modal.open(CustomModal, overlayConfig);
```

Note that we are pre-setting the context (num1,num2) since we can't set it via the builder in a fluent api like manner... this is because `BSModalContextBuilder` doesn't have these functions defined.

```ts
builder.num1(2).num(3) // <-- error
```
It will error since these function does not exist, for them to exist you will need to create a builder class of you'r own, having these functions defined.

You can avoid creating a new builder class by setting them in the constructor:
```ts
          const builder = new BSModalContextBuilder<CustomModalContext>(
            { num1: 2, num2: 3 } as any, // here we pre-set the context
            ['num1', 'num2'], // the builder factory will generate 2 functions
            CustomModalContext // hinting the builder we're using this context class so it will init it.
          );
```

But it will not reflect in type script... you'll need to cast to any or something or use TS intersection types..

to simplify things I can change the type of in `inElement` to accept a `viewContainerRef` (id or `ViewContainerRef`) and reduce the 2 steps to 1 but this is a breaking change... i'll think about it.


In the demo app, see [this example](https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/app/bootstrap-demo/bootstrap-demo-page/bootstrap-demo-page.ts#L44-L54) of custom modal, replace the highlight lines with the following code and you will see an inElement custom modal.

```ts
          const builder = new BSModalContextBuilder<CustomModalContext>(
            { num1: 2, num2: 3 } as any,
            undefined,
            CustomModalContext
          );

          let overlayConfig: OverlayConfig = {
            viewContainer: 'demo-head',
            context: builder.inElement(true).toJSON()
          };

          return this.modal.open(CustomModal, overlayConfig);
```

**Comment by scottmbulloch** [comment]
I am updating an app that was using version 0.0.3 and Angular2 beta 7! I am on version 2.0.0-beta.10 and RC5 now, lots of changes. Anyway, just added the `viewContainer: 'ID'` and `inElement(true)` into the OverlayConfig and it's working great, knew I was missing something simple. Thanks for detailed explanation!
