### ISSUE TITLE
Error is coming while creating Custom Dialog

### ISSUE THREAD

**Issue by kunjee17** [shlomiassaf/angular2-modal#248]
Hi, I am trying in adding Custom Modal in project. But while invoking it I am getting error. I am unable to find out a way to debug it. Can you please help me out with this. 

Here is error message I am getting 

> Error in ./ModalOverlay class ModalOverlay - inline template:2:14 caused by: No component factory found for CustomModal

![custommodal](https://cloud.githubusercontent.com/assets/960605/20135660/e5e263c2-a696-11e6-9aa9-b0ac2f334c8f.PNG)

Above is the trace I am getting. Just help me debug so I can even further debug the issue.

**Comment by shlomiassaf** [comment]
This is related to angular and how angular 2 works.

put the component you want to project in the `enteryComponents` array in the module (same module where you declare/export that component)

Since your `CustomModal` is not appearing in any template angular does not create a factory for it (in the compilation process) so this is how you tell it to do it.

**Comment by russosalv** [comment]
Hi can you explain better this, i have same problem of it
following your code http://plnkr.co/edit/ZAZqZu?p=preview

**Comment by MA-Maddin** [comment]
@russosalv 
in `app.module.ts`:

```
import { CustomModal } from './some/path/file-containing-custom-modal.component';
// ...
@NgModule({
  declarations: [
    // ...
    CustomModal,
  ],
  // ...
  entryComponents: [
    CustomModal,
  ]
})
export class AppModule { }
```
