### ISSUE TITLE
AOT Broken in Angular 2.4

### ISSUE THREAD

**Issue by moloch--** [shlomiassaf/angular2-modal#273]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

```
➜  ng build --aot
 12% building modules 23/24 modules 1 active ...de_modules/css-loader/lib/css-base.jsFailed on type {"filePath":"/Users/myuser/git/myapp/gui/myapp-client/node_modules/angular2-modal/esm/models/overlay-context.d.ts","name":"OverlayContextBuilder","members":[]} with error Error: Error encountered resolving symbol values statically. Expression form not supported (position 89:30 in the original .ts file), resolving symbol OverlayContextBuilder in /Users/myuser/git/myapp/gui/myapp-client/node_modules/angular2-modal/esm/models/overlay-context.d.ts
Hash: 2d74410ff3ceae8d6e3a
Time: 8921ms
chunk    {0} styles.bundle.js, styles.bundle.map (styles) 333 kB {4} [initial] [rendered]
chunk    {1} scripts.bundle.js, scripts.bundle.map (scripts) 1.16 MB {4} [initial] [rendered]
chunk    {2} main.bundle.js, main.bundle.map (main) 1.7 kB {3} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 1.06 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

ERROR in Error encountered resolving symbol values statically. Expression form not supported (position 89:30 in the original .ts file), resolving symbol OverlayContextBuilder in /Users/myuser/git/myapp/gui/myapp-client/node_modules/angular2-modal/esm/models/overlay-context.d.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/myuser/git/myapp/gui/myapp-client/src'
 @ ./src/main.ts 4:0-74
 @ multi main

ERROR in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
Module not found: Error: Can't resolve '/Users/myuser/git/myapp/gui/myapp-client/src/$$_gendir' in '/Users/myuser/git/myapp/gui/myapp-client/node_modules/@angular/core/src/linker'
 @ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js 69:15-36 85:15-102
 @ ./~/@angular/core/src/linker.js
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ ./src/main.ts
 @ multi main
```

Builds correctly without `--aot`

* **Please tell us about your environment:**

- Angular version: 2.4.0
- Browser: [all]

`"angular2-modal": "^2.0.2"`

```
➜  ng --version
angular-cli: 1.0.0-beta.22-1
node: 7.2.0
os: darwin x64
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Possibly related -> [https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.7ev0neev7](https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.7ev0neev7)

**Comment by bniehuser** [comment]
based on a quick look at the file and the reference at the end of the original report, it would seem that the problem is likely either DEFAULT_VALUES or DEFAULT_SETTERS -- without having looked further, either exporting or inlining DEFAULT_SETTERS may clear the problem, otherwise it may require inlining both (although i'm guessing that DEFAULT_VALUES are exported for a reason).  don't have time today to pull, change, and test in my setup, but if not resolved soon i'll have to give it a go.

**Comment by shlomiassaf** [comment]
@bniehuser It's not related to the DEFAULT_SETTINGS.

The problem is actually not 2.4 specific....

Both `ModalContextBuilder` and `OverlayContextBuilder` are decorated with `@Injectable` which makes no sense, they are not services... it's probably something historical.

Anyway, they both have Generic types in the constructor which doesn't work with DI :)

So in 2.4 they improved the compiler to find these things..

Anyway, I removed it in #274 
I still don't release a version, I'm not sure AOT compiled lib works with 2.1.x

**Comment by FriOne** [comment]
Finnaly I got my AOT compilation work but got problems with your module :)
It is the best modal module in the community for now. Thank you for it! AOT compilation is very importatnt for me, if you don't release it what will be a trigger to do that?

**Comment by shlomiassaf** [comment]
I will release it, I just need to verify the version of angular it supports using

**Comment by dzonatan** [comment]
@shlomiassaf any update on this? Can we help you somehow?

**Comment by verasztol** [comment]
+1

**Comment by raphaa** [comment]
Any updates here? :)

**Comment by NisStrom** [comment]
When is this getting into a release bundle?

**Comment by dzonatan** [comment]
@NisStrom it's already in `2.0.3`

**Comment by DBuit** [comment]
I'am trying to aot compile my project but getting the following error: ChartModule function calls are not supported. Someone can help me what the problem is? I am using version 2.0.3

The error:
<img width="640" alt="screen shot 2017-02-16 at 14 44 49" src="https://cloud.githubusercontent.com/assets/17079647/23023557/80b7eeaa-f456-11e6-8d21-924c9306fd45.png">

**Comment by srivastavaapoorvkumar** [comment]
Post AOT compilation Im unable to open any module because CSSBackdrop's factory is not found. This is happening because of two CSSBackdrop that I find in app.js. First is one is being used to build the factory map while when the modal actually needs to open it is requesting to create component refrencing the second CSSBackdrop.
