### ISSUE TITLE
Missing scroll behavior for long modal

### ISSUE THREAD

**Issue by bertrandg** [shlomiassaf/angular2-modal#31]
With [original bootstrap modal](http://getbootstrap.com/javascript/#modals), when we open a modal, a class `modal-open` is added on `body` tag to add a `overflow: hidden;` and mask main scrollbar.
And a `overflow-y: auto;` rule is (automatically due to css rule) added on the `.modal-open .modal` element to allow scroll to the bottom of the modal when needed.

Thanks for your lib, it's a really needed one.

**Comment by shlomiassaf** [comment]
Hi

I've added support in 0.0.6.

I'm not happy with it because it couples the module with the DOM for that feature.
<body> might or might not be a part of Angular, it depends what the developer chose for it's "main", usually in all demo's they show to use <app> and leave body out of angular... So, I can't build a <body> directive cause if it's not there it wont work.

I can only access it via DOM Adapter.

Another issue is modal within element, I didn't handle it, the body because the containing element in this case and I don't handle such cases.... for now at least.

**Comment by bertrandg** [comment]
Thanks for adding it! :)
Yes, I see the problem and don't see proper way to solve it..
