### ISSUE TITLE
modal is on the left

### ISSUE THREAD

**Issue by ronencamera** [shlomiassaf/angular2-modal#51]
i upgraded from 0.0.4 to the latest version. Now my modal is aligned to the left.

how do i fix this?

**Comment by shlomiassaf** [comment]
I need more info.

The code you use for opening the modal.
Angular 2 version...

**Comment by kleinech** [comment]
Use the class: `modal-dialog`
```
modal.alert()
            .title('Title')
            .size('lg')
            .dialogClass('modal-dialog')
            .body('<h1>Section</h1>')
            .open();
```

**Comment by shlomiassaf** [comment]
@kleinech You're right but it is set by default... so there's not reason to actually set it to `modal-dialog`

**Comment by tlorenzetti** [comment]
Also in my case the class `modal-dialog` it's not applied if not explicitly set

**Comment by yahyaKacem** [comment]
@ronencamera I had that problem when I removed this lines from the main.ts file:
[line 11](https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/bootstrap.ts#L11) [line 18](https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/bootstrap.ts#L18) in the example that problem went away when I put those line back.

**Comment by shlomiassaf** [comment]
Yep, you're right
The problem is in [Modal.ts](https://github.com/shlomiassaf/angular2-modal/blob/c37419f0d484af7d69c607f948b3ff729fc144d3/src/components/angular2-modal/providers/Modal.ts#L37)

When no `ModalConfig` I create a new one using the internal defaults, but to user the internal defaults I need to normalise it

So from 
```ts
value: (defaultConfig) ? ModalConfig.makeValid(defaultConfig) : new ModalConfig(),
```

We need:
```ts
value: (defaultConfig) ? ModalConfig.makeValid(defaultConfig) : ModalConfig.makeValid(new ModalConfig()),
```
I will post a commit, thanks!
