### ISSUE TITLE
modal service not set

### ISSUE THREAD

**Issue by kvgros** [shlomiassaf/angular2-modal#61]
I seem to have everything referenced correctly but get the js error 'Configuration Error: modal service not set' whenever I call a line such as:

this.modal.prompt().title(title).body(body).okBtn(okButton).open();

Could be how I am using the library but for now we are just testing it out  We are using commonJS if that may be somehow related to the issue.

My bootstrap line looks like:

bootstrap(RootComponent, [HTTP_PROVIDERS, provide(ModalConfig, { useValue: new ModalConfig('sm', true, 81) })]);

Any other configuration I'm missing to overcome the 'modal service not set'?

**Comment by shlomiassaf** [comment]
@kvgros 
`Configuration Error: modal service not set` comes from `ModalAwarePreset.ts`
See [here](https://github.com/shlomiassaf/angular2-modal/blob/master/src/components/angular2-modal/presets/base/ModalAwarePreset.ts#L74)

This is related to using the Fluent API to open a modal.

Basically what happens is that along the process of constructing a preset (so you could use the fluent API) the modal is set internally, this is so you wouldn't have to do:

```
// in class constructor:private modal: Modal
modal.alert()
    .modal(this.modal)
    .title('Hello World')
    .body('In Angular 2')
    .open();
```

The preset must have a reference to the "Modal" instance so it can fire `open`.

`ModalAwarePreset.ts` is just a base class, the actual modal assignment happens in `OneButtonPreset` which is a concrete preset.
It gets a modal as a value in the constructor....

When you call `modal.prompt()` this get invoked:
```ts
prompt(): OneButtonPreset {
        return new OneButtonPreset(this, <any>{ isBlocking: true, keyboard: null });
    }
```

So, the first param in the ctor for `OneButtonPreset` is `this` which is the instance of `Modal` so the error is very strange...

Is there any change you are importing direct files instead of the entry file?

**Comment by shlomiassaf** [comment]
stale, closing...
