### ISSUE TITLE
Modal closing when clicking anywhere on form.

### ISSUE THREAD

**Issue by Sunnyque** [shlomiassaf/angular2-modal#7]
Any click inside modal frame closes a modal - this is not right. Need a way to disable it (blocking mode is a way around)

Also there is a lot of TSLint "errors" in sources and npm ready package is really welcome

Thanks for your work!

**Comment by shlomiassaf** [comment]
Hi,
Thanks.

Fixed the click bug.
Added linting.

As for NPM package, I will have to restructure parts of the code, add `.npmignore` and configure webpack to make a build for the component only (right now it also compiles the demo site as well)

Since angular is still in beta I dont know how much it will help but I will work on it.

**Comment by shlomiassaf** [comment]
Please try to use it as a package
```
    npm install angular2-modal --save
```

I would like to know if it worked.

**Comment by Sunnyque** [comment]
Seems all my issues has been fixed, thank you for fast reply! npm package is also usable for me. Nice way of modal customization it is really easy to implement my own modals
