### ISSUE TITLE
Use of ngModel inside modal template fires an exception on dialog open

### ISSUE THREAD

**Issue by sunnyque** [shlomiassaf/angular2-modal#9]
I'am not sure is this issue exactly of angular2-modal but here some info it might be useful for someone else

I got a trouble using angular2-modal when decided to implement input with ngModel inside modal template e.g. 
```
<input type="text" class="form-control" required [(ngModel)]="data">
```

after that I got an exception while opening a modal dialog: EXCEPTION: No provider for e! (t -> Token NgValueAccessor -> e -> e)

while trying to solve a problem I found similar issue:

http://stackoverflow.com/questions/34606534/angular2-no-provider-for-renderer-ngmodel-token-ngvalueaccessor-defaultv

answers in that topic helps me to fix my problem:

Insert additional provide to bindings when calling dialog open
```javascript
        let bindings = Injector.resolve([
            provide(ICustomModal, {useValue: DemoPage.modalData[type]}),
            provide(Renderer, { useValue: this._renderer}) // here we go. constructor(private _renderer: Renderer)
        ]);
```
after those changes ngModel works as expected. 

so could you add a reference to Renderer inside dialog source or we need to use this workaround? I'am expecting usage of forms inside modals will be often so it might help to save some time

**Comment by sunnyque** [comment]
IterableDiffers (from angular2/core) for NgFor support.

Same as described in existing issue https://github.com/shlomiassaf/angular2-modal/issues/6

I'am closing this issue because already one opened but it will be great if you describe this behavior and workaround in documentation or/and include one additional example to your demos, thanks

**Comment by shlomiassaf** [comment]
I'm not near my pc, but tomorrow I'll check.

I think that setting these directives in the bootstrap invocation should solve this, they will be globally mapped, like ng1 DI ...

There should be 1 common collection for most of them, maybe several collections.

If the DynamicComponentLoader would have accepted an injector I was sure it would have work but since it get a collection of resolved providers I'm not sure... (Only loadAsRoot in DynamicCompinentLoader requires an injector, which makes sense)
Basically

**Comment by shlomiassaf** [comment]
Added example how to workaround this issue, see readme.md for more details or review the [commit](https://github.com/shlomiassaf/angular2-modal/commit/22497b67dff6f087fe235653b3f1564fe2fe50d8)
