### ISSUE TITLE
Component in body?

### ISSUE THREAD

**Issue by iradovanovic** [shlomiassaf/angular2-modal#96]
Hi.

Is it possible to use other component in DIALOG body?

If i try:
` .body('<my-comp></my-comp>')`
won't throw an error but also won't render components html.

**Comment by shlomiassaf** [comment]
`.body()` support HTML but does not support HTML compilation.
This is virtually not possible in Angular 2 since templates have to be static, i.e known upfront.

To provide a custom component you need to specify the component when opening it.
This is only available via the `open()` method, `alert`, `propmt` and `confirm` are not supported out of the box tough it might be possible.

See the [bootstrap demo](https://github.com/shlomiassaf/angular2-modal/tree/master/src/demo/app/bootstrap-demo/bootstrap-demo-page) for an example how to use a custom modal, the custom modal is [here](https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/app/bootstrap-demo/bootstrap-demo-page/custom-modal-sample.ts)

**Comment by ansuman273** [comment]
I need to put components in the body is it possible now @shlomiassaf

**Comment by splutz** [comment]
@shlomiassaf In my opinion this is quite convoluted.... why custom component templates are only supported in some of the modal presentation methods but not others? Will they be supported in the future? A consumer of this angular API should be able to put whatever tags they wish inside `.body()`.

**Comment by DelphiWorlds** [comment]
@splutz You might be able to do something like Gbacc's answer, in this report:
https://github.com/shlomiassaf/ngx-modialog/issues/224
